// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type SliceSectionDocumentDataSlicesSlice =
  | TestimonialsSectionSlice
  | TeamSectionSlice;

/**
 * Content for Slice Section documents
 */
interface SliceSectionDocumentData {
  /**
   * Slice Zone field in *Slice Section*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: slice_section.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<SliceSectionDocumentDataSlicesSlice>;
}

/**
 * Slice Section document from Prismic
 *
 * - **API ID**: `slice_section`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SliceSectionDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<SliceSectionDocumentData>,
    "slice_section",
    Lang
  >;

export type AllDocumentTypes = SliceSectionDocument;

/**
 * Primary content in *TeamSection → Primary*
 */
export interface TeamSectionSliceDefaultPrimary {
  /**
   * Section Title field in *TeamSection → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Our Team
   * - **API ID Path**: team_section.primary.section_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  section_title: prismic.TitleField;
}

/**
 * Primary content in *TeamSection → Items*
 */
export interface TeamSectionSliceDefaultItem {
  /**
   * Name field in *TeamSection → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Name of the team member
   * - **API ID Path**: team_section.items[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Position field in *TeamSection → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Position of the team member
   * - **API ID Path**: team_section.items[].position
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  position: prismic.KeyTextField;

  /**
   * Profile Picture field in *TeamSection → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: team_section.items[].profile_picture
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  profile_picture: prismic.ImageField<never>;
}

/**
 * Default Variation variation for TeamSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default variation displaying team members with their names, positions, and profile pictures.
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TeamSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TeamSectionSliceDefaultPrimary>,
  Simplify<TeamSectionSliceDefaultItem>
>;

/**
 * Primary content in *TeamSection → Primary*
 */
export interface TeamSectionSliceDarkPrimary {
  /**
   * Section Title field in *TeamSection → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Our Team
   * - **API ID Path**: team_section.primary.section_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  section_title: prismic.TitleField;
}

/**
 * Primary content in *TeamSection → Items*
 */
export interface TeamSectionSliceDarkItem {
  /**
   * Name field in *TeamSection → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Name of the team member
   * - **API ID Path**: team_section.items[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Position field in *TeamSection → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Position of the team member
   * - **API ID Path**: team_section.items[].position
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  position: prismic.KeyTextField;

  /**
   * Profile Picture field in *TeamSection → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: team_section.items[].profile_picture
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  profile_picture: prismic.ImageField<never>;
}

/**
 * dark variation for TeamSection Slice
 *
 * - **API ID**: `dark`
 * - **Description**: Default variation displaying team members with their names, positions, and profile pictures.
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TeamSectionSliceDark = prismic.SharedSliceVariation<
  "dark",
  Simplify<TeamSectionSliceDarkPrimary>,
  Simplify<TeamSectionSliceDarkItem>
>;

/**
 * Slice variation for *TeamSection*
 */
type TeamSectionSliceVariation = TeamSectionSliceDefault | TeamSectionSliceDark;

/**
 * TeamSection Shared Slice
 *
 * - **API ID**: `team_section`
 * - **Description**: The Team Section is made of a card for each team member, each card contains a name, a position, and a profile picture.
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TeamSectionSlice = prismic.SharedSlice<
  "team_section",
  TeamSectionSliceVariation
>;

/**
 * Primary content in *TestimonialsSection → Primary*
 */
export interface TestimonialsSectionSliceDefaultPrimary {
  /**
   * Section Title field in *TestimonialsSection → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter the title for the testimonials section
   * - **API ID Path**: testimonials_section.primary.section_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  section_title: prismic.KeyTextField;
}

/**
 * Primary content in *TestimonialsSection → Items*
 */
export interface TestimonialsSectionSliceDefaultItem {
  /**
   * Name field in *TestimonialsSection → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials_section.items[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Position field in *TestimonialsSection → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials_section.items[].position
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  position: prismic.KeyTextField;

  /**
   * Company field in *TestimonialsSection → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials_section.items[].company
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  company: prismic.KeyTextField;

  /**
   * Quote field in *TestimonialsSection → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter the testimonial quotation
   * - **API ID Path**: testimonials_section.items[].quote
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  quote: prismic.RichTextField;
}

/**
 * Default Variation variation for TestimonialsSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default variation displaying a collection of testimonials.
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimonialsSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TestimonialsSectionSliceDefaultPrimary>,
  Simplify<TestimonialsSectionSliceDefaultItem>
>;

/**
 * Primary content in *TestimonialsSection → Primary*
 */
export interface TestimonialsSectionSliceDarkPrimary {
  /**
   * Section Title field in *TestimonialsSection → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter the title for the testimonials section
   * - **API ID Path**: testimonials_section.primary.section_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  section_title: prismic.KeyTextField;
}

/**
 * Primary content in *TestimonialsSection → Items*
 */
export interface TestimonialsSectionSliceDarkItem {
  /**
   * Name field in *TestimonialsSection → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials_section.items[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Position field in *TestimonialsSection → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials_section.items[].position
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  position: prismic.KeyTextField;

  /**
   * Company field in *TestimonialsSection → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials_section.items[].company
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  company: prismic.KeyTextField;

  /**
   * Quote field in *TestimonialsSection → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter the testimonial quotation
   * - **API ID Path**: testimonials_section.items[].quote
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  quote: prismic.RichTextField;
}

/**
 * dark variation for TestimonialsSection Slice
 *
 * - **API ID**: `dark`
 * - **Description**: Default variation displaying a collection of testimonials.
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimonialsSectionSliceDark = prismic.SharedSliceVariation<
  "dark",
  Simplify<TestimonialsSectionSliceDarkPrimary>,
  Simplify<TestimonialsSectionSliceDarkItem>
>;

/**
 * Slice variation for *TestimonialsSection*
 */
type TestimonialsSectionSliceVariation =
  | TestimonialsSectionSliceDefault
  | TestimonialsSectionSliceDark;

/**
 * TestimonialsSection Shared Slice
 *
 * - **API ID**: `testimonials_section`
 * - **Description**: Displays a list of testimonials, each one contains a name, a position, a company, and a quote.
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimonialsSectionSlice = prismic.SharedSlice<
  "testimonials_section",
  TestimonialsSectionSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      SliceSectionDocument,
      SliceSectionDocumentData,
      SliceSectionDocumentDataSlicesSlice,
      AllDocumentTypes,
      TeamSectionSlice,
      TeamSectionSliceDefaultPrimary,
      TeamSectionSliceDefaultItem,
      TeamSectionSliceDarkPrimary,
      TeamSectionSliceDarkItem,
      TeamSectionSliceVariation,
      TeamSectionSliceDefault,
      TeamSectionSliceDark,
      TestimonialsSectionSlice,
      TestimonialsSectionSliceDefaultPrimary,
      TestimonialsSectionSliceDefaultItem,
      TestimonialsSectionSliceDarkPrimary,
      TestimonialsSectionSliceDarkItem,
      TestimonialsSectionSliceVariation,
      TestimonialsSectionSliceDefault,
      TestimonialsSectionSliceDark,
    };
  }
}
