// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  team_section: dynamic(() => import("./TeamSection")),
  testimonials_section: dynamic(() => import("./TestimonialsSection")),
};
